In [18]:
import pandas as pd

In [19]:
amazon_df=pd.read_csv(r"C:\Users\nandana\Downloads\Amazon Sale Report.csv")

C:\Users\nandana\AppData\Local\Temp\ipykernel_13160\2372435028.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  amazon_df=pd.read_csv(r"C:\Users\nandana\Downloads\Amazon Sale Report.csv")

In [20]:
amazon_df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [21]:
amazon_df.shape

(128975, 24)

In [22]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [23]:
amazon_df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [24]:
amazon_df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [25]:
amazon_df.Status.value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [26]:
amazon_df.currency.value_counts()

currency
INR    121180
Name: count, dtype: int64

In [27]:
amazon_df["ship-country"].value_counts()

ship-country
IN    128942
Name: count, dtype: int64

In [28]:
amazon_df=amazon_df.drop(columns=["index","Unnamed: 22","ASIN","SKU","promotion-ids","fulfilled-by","currency","ship-country"])

In [29]:
amazon_df.shape

(128975, 16)

In [30]:
amazon_df.isnull().sum()

Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
Category                 0
Size                     0
Courier Status        6872
Qty                      0
Amount                7795
ship-city               33
ship-state              33
ship-postal-code        33
B2B                      0
dtype: int64

In [31]:
amazon_df["Date"]=pd.to_datetime(amazon_df["Date"])

C:\Users\nandana\AppData\Local\Temp\ipykernel_13160\1949141652.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon_df["Date"]=pd.to_datetime(amazon_df["Date"])

In [32]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Category            128975 non-null  object
 8   Size                128975 non-null  object
 9   Courier Status      122103 non-null  object
 10  Qty                 128975 non-null  int64
 11  Amount              121180 non-null  float64
 12  ship-city           128942 non-null  object
 13  ship-state          128942 non-null  object
 14  ship-postal-code    128942 non-null  float64
 15  B2B                 128975 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(11)
memory usage: 14.9+ MB

In [33]:
amazon_df["Courier Status"]=amazon_df["Courier Status"].fillna(amazon_df["Courier Status"].mode()[0])

In [34]:
amazon_df["Amount"]=amazon_df["Amount"].fillna(amazon_df["Amount"].median())

In [35]:
amazon_df["ship-city"]=amazon_df["ship-city"].fillna(amazon_df["ship-city"].mode()[0])

In [36]:
amazon_df["ship-state"]=amazon_df["ship-state"].fillna(amazon_df["ship-state"].mode()[0])

In [37]:
amazon_df["ship-postal-code"]=amazon_df["ship-postal-code"].fillna(amazon_df["ship-postal-code"].mode()[0])

In [38]:
amazon_df.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
Category              0
Size                  0
Courier Status        0
Qty                   0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
B2B                   0
dtype: int64

In [39]:
amazon_df.duplicated().sum()

np.int64(7)

In [40]:
amazon_df=amazon_df.drop_duplicates()

In [41]:
amazon_df.duplicated().sum()

np.int64(0)

In [42]:
from sklearn.preprocessing import LabelEncoder
columns_encode=["Sales Channel ","Fulfilment","ship-service-level","Style","Category","Size","Courier Status","ship-city","ship-state"]
for col in columns_encode:
    le=LabelEncoder()
    amazon_df[col]=le.fit_transform(amazon_df[col])

In [43]:
from sklearn.preprocessing import LabelEncoder
le_status=LabelEncoder()
le_status.fit_transform(amazon_df["Status"])

array([0, 5, 3, ..., 3, 3, 3], shape=(128968,))

In [44]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128968 entries, 0 to 128974
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128968 non-null  object
 1   Date                128968 non-null  datetime64[ns]
 2   Status              128968 non-null  object
 3   Fulfilment          128968 non-null  int64
 4   Sales Channel       128968 non-null  int64
 5   ship-service-level  128968 non-null  int64
 6   Style               128968 non-null  int64
 7   Category            128968 non-null  int64
 8   Size                128968 non-null  int64
 9   Courier Status      128968 non-null  int64
 10  Qty                 128968 non-null  int64
 11  Amount              128968 non-null  float64
 12  ship-city           128968 non-null  int64
 13  ship-state          128968 non-null  int64
 14  ship-postal-code    128968 non-null  float64
 15  B2B                 128968 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(10), object(2)
memory usage: 15.9+ MB

In [45]:
q1=amazon_df["Amount"].quantile(0.25)
q3=amazon_df["Amount"].quantile(0.75)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q3+1.5*iqr
outliers=amazon_df[(amazon_df["Amount"]<lower)|(amazon_df["Amount"]>upper)]
print(outliers)
print(len(outliers))

                   Order ID       Date                        Status  \
80      408-4069830-3819562 2022-04-30                       Shipped
102     408-7698765-2294756 2022-04-30  Shipped - Delivered to Buyer
146     171-0131752-2560336 2022-04-30  Shipped - Delivered to Buyer
226     407-4936046-5852304 2022-04-30                     Cancelled
243     408-2759943-9849959 2022-04-30                       Shipped
...                     ...        ...                           ...
128811  404-8080630-3948329 2022-06-01                       Shipped
128846  407-3299391-4191514 2022-06-01                     Cancelled
128873  405-4724097-1016369 2022-06-01  Shipped - Delivered to Buyer
128911  171-2686043-8605144 2022-05-31                       Shipped
128957  402-8261465-0622733 2022-05-31                       Shipped

        Fulfilment  Sales Channel   ship-service-level  Style  Category  Size  \
80               0               0                   0   1346         5     0
102              1               0                   1   1249         5    10
146              1               0                   1   1317         5     6
226              1               0                   1   1317         5    10
243              0               0                   0   1324         5    10
...            ...             ...                 ...    ...       ...   ...
128811           0               0                   0   1027         5     2
128846           0               0                   0    326         5     6
128873           1               0                   1    165         5     7
128911           0               0                   0    302         5     8
128957           0               0                   0    302         5     6

        Courier Status  Qty   Amount  ship-city  ship-state  ship-postal-code  \
80                   1    1  1281.00       4204          61          700048.0
102                  1    1  1338.00        135          28          421502.0
146                  1    1  1399.00        667          59          225001.0
226                  1    0  1249.11       2620          19          122001.0
243                  1    1  1338.00       3712          61          700051.0
...                ...  ...      ...        ...         ...               ...
128811               1    1  1399.00       2772          19          122001.0
128846               2    1  1364.00       3001          57          500081.0
128873               1    1  1523.00        107           1          524315.0
128911               1    1  1349.00       6158          28          411002.0
128957               1    1  1349.00       6583          22          834002.0

          B2B
80      False
102     False
146     False
226     False
243     False
...       ...
128811  False
128846  False
128873  False
128911  False
128957  False

[4177 rows x 16 columns]
4177

In [46]:
print(lower)
print(upper)

-9.0
1239.0

In [51]:
amazon_df=amazon_df[(amazon_df["Amount"]>=lower)&(amazon_df["Amount"]<=upper)]

In [52]:
print(outliers)

Empty DataFrame
Columns: [Order ID, Date, Status, Fulfilment, Sales Channel , ship-service-level, Style, Category, Size, Courier Status, Qty, Amount, ship-city, ship-state, ship-postal-code, B2B]
Index: []

In [53]:
amazon_df.Amount.min()

0.0

In [54]:
amazon_df.Amount.max()

1238.0

In [55]:
amazon_df.Amount.mean()

np.float64(620.2609689000008)

In [56]:
amazon_df.Amount.std()

235.3736292731647

In [57]:
print(amazon_df["Amount"].describe())

count    124791.000000
mean        620.260969
std         235.373629
min           0.000000
25%         455.000000
50%         605.000000
75%         759.000000
max        1238.000000
Name: Amount, dtype: float64

In [58]:
amazon_df.shape

(124791, 16)